config/routes.rb
Rails.application.routes.draw do
  root to: 'projects#index'
  devise_for :users
  resources :projects do
    resources :kpts, only: %i(index new create)
  end
  resources :keep_things, only: %i(index)
  resources :try_things, only: %i(index update)
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/keep_thing.rb
class KeepThing < ApplicationRecord
  belongs_to :kpt, inverse_of: :keep_things

  validates :content, presence: true
end

app/models/kpt.rb
class Kpt < ApplicationRecord
  has_many :keep_things, inverse_of: :kpt
  has_many :problem_things, inverse_of: :kpt
  has_many :try_things, through: :problem_things
  accepts_nested_attributes_for :keep_things, reject_if: :all_blank
  accepts_nested_attributes_for :problem_things, reject_if: :all_blank
  belongs_to :project

  def build_relation_things
    keep_things.build
    problem_thing = problem_things.build
    problem_thing.try_things.build
  end
end

app/models/problem_thing.rb
class ProblemThing < ApplicationRecord
  has_many :try_things, inverse_of: :problem_thing
  belongs_to :kpt, optional: true
  accepts_nested_attributes_for :try_things, reject_if: :all_blank

  validates :content, presence: :true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :project_memberships, dependent: :destroy
  has_many :users, through: :project_memberships
  has_many :kpts, dependent: :destroy

  validates :name, presence: true

  def last_kpt
    kpts.order(created_at: :desc).last
  end
end

app/models/project_membership.rb
class ProjectMembership < ApplicationRecord
  belongs_to :user, inverse_of: :project_memberships
  belongs_to :project, inverse_of: :project_memberships
end

app/models/try_thing.rb
class TryThing < ApplicationRecord
  belongs_to :problem_thing, optional: true
  belongs_to :kpt

  validates :content, presence: true

  # create_keep!でいいのでは
  # keep!でもいいかも？
  # updateも入っているのでメソッド名を工夫する必要がある
  def create_keep_things_from_try_thing!
    ActiveRecord::Base.transaction do
      # problem_thing.kptが適用されているかもテストする
      # belongs_toでkptが必要ではないか？
      # problem_thing.kptがオプショナルだから落ちるかもしれない
      kpt.keep_tings.create!(content: content)
      KeepThing.create!(content: content, kpt: problem_thing.kpt)
      self.update!(complete: true)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :project_memberships, dependent: :destroy
  has_many :projects, through: :project_memberships
  has_many :kpts, through: :projects, source: :kpts
  has_many :keep_things, through: :kpts, source: :keep_things
  has_many :problem_things, through: :kpts, source: :problem_things
  has_many :try_things, through: :kpts, source: :try_things
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/keep_things_controller.rb
class KeepThingsController < ApplicationController
  def index
    @keep_things = current_user.keep_things.order(id: :desc)
  end
end

app/controllers/kpts_controller.rb
class KptsController < ApplicationController
  before_action :set_project

  def index
    @kpts = @project.kpts.order(id: :desc)
  end

  def new
    @last_kpt = @project.last_kpt
    @kpt = @project.kpts.build
    @kpt.build_relation_things
  end

  def create
    @kpt = @project.kpts.build(kpt_params)
    if @kpt.save
      redirect_to project_kpts_path(@project)
    else
      render :new
    end
  end

  private

  def kpt_params
    params.require(:kpt).permit(
      :target_on,
      :description,
      keep_things_attributes: [:id, :_destroy, :content],
      problem_things_attributes: [:id, :_destroy, :content, try_things_attributes: [:id, :_destroy, :content]]
    )
  end

  def set_project
    @project = current_user.projects.find(params[:project_id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = current_user.projects.order(id: :desc)
  end
  def new
    @project = current_user.projects.build
  end

  def create
    @project = current_user.projects.build(project_params)
   if @project.save
     redirect_to root_path
   else
     render :new
   end
  end

  private
  def project_params
    params.require(:project).permit(:name)
  end
end

app/controllers/try_things_controller.rb
class TryThingsController < ApplicationController
  def index
    @try_things = current_user.try_things.order(created_at: :desc)
  end

  def update
    @try_thing = TryThing.find(params[:id])
    @try_thing.create_keep_things_from_try_thing!
    respond_to :js
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/keep_things/index.html.haml
%table.table.table-bordered
  %tr.table-success
    %th Keep
    - @keep_things.each do |keep_thing|
      %tr
        %td
          - if keep_thing.complete?
            %span.badge.badge-info.mr-3
              習慣化
          - else
            %span.badge.badge-warning.mr-3
              実施中
          = keep_thing.content
          %p.d-inline.float-right
            = keep_thing.created_at.strftime('%Y年%m月%d日')

app/views/kpts/_keep_thing_fields.html.haml
.nested_fields.mb-3
  .form-inline
    = f.input :content, as: :string, label: false, wrapper_html: { class: 'form-inline keep-things-fields__input-wrapper' }, input_html: { class: 'keep-things-fields__input spec__keep-things-input' }
    = link_to_remove_association "削除", f, class: 'btn btn-danger'

app/views/kpts/_problem_thing_fields.html.haml
%h2.h3
  Problem
.nested_fields.mb-3{ style: 'overflow: hidden'}
  = f.input :content, label: false, input_html: { class: 'js-problem-input spec__problem-things-input' }
  = link_to_remove_association "削除", f, class: 'btn btn-danger float-right'
  .try-things
    = f.simple_fields_for :try_things do |try_thing|
      = render 'try_thing_fields', f: try_thing
    .links
      = link_to_add_association 'T追加', f, :try_things, class: 'btn btn-warning float-right'

app/views/kpts/_try_thing_fields.html.haml
.nested_fields
  %h2.h3
    Try
  = f.input :content, label: false, as: :string, input_html: { class: 'spec__try-things-input'}

app/views/kpts/index.html.haml
- if @kpts.blank?
  .alert.alert-warning
    ふりかえりがありません
- else
  - @kpts.each do |kpt|
    .col-lg-10.offset-lg-1.mb-3
      .card
        .card-body
          %h5.card-title= kpt.target_on.strftime('%Y年%m月%d日')
          %table.table.table-bordered
            %tr.table-success
              %th Keep
            - kpt.keep_things.each do |keep_thing|
              %tr
                %td.spec__keep-thing-content
                  = keep_thing.content
          %table.table.table-bordered
            %tr.table-danger
              %th Problem
              - kpt.problem_things.each do |problem_thing|
                %tr
                  %td.spec__problem-thing-content= problem_thing.content
                %tr
                  - problem_thing.try_things.each do |try_thing|
                    %td
                      %span.badge.badge-primary.mr-3
                        Try
                      %p.font-weight-bold.d-inline.spec__try-thing-content
                        = try_thing.content
          = simple_format kpt.description, class: 'card-text'

app/views/kpts/new.html.haml
%h1.page-header
  ふりかえり
- if @last_kpt.present?
  %table.table.table-bordered.mb-5
    %tr.table-primary
      %th 前回のTry
      - @last_kpt.try_things.each do |try_thing|
        %tr
          %td
            = try_thing.content
            - if try_thing.complete?
              %span.btn.btn-sm.btn-outline-secondary.disabled.float-right
                Keep済み
            - else
              = link_to 'Keepにする',
                        try_thing_path(try_thing),
                        method: :patch,
                        class: 'btn btn-sm btn-outline-success float-right js-btn-change-keep',
                        remote: true,
                        data: { try_id: try_thing.id, confirm: 'Keepにしますか？' }
= simple_form_for [@project, @kpt] do |f|
  = f.input :target_on
  .card.p-3.mb-3
    %h2.h3
      Keep
    = f.simple_fields_for :keep_things do |keep_thing|
      = render 'keep_thing_fields', f: keep_thing
      .links
        = link_to_add_association '+', f, :keep_things, class: 'btn btn-info spec__add-keep-things'
  .card.p-3.mb-3.js-problem
    = f.simple_fields_for :problem_things do |problem_thing|
      = render 'problem_thing_fields', f: problem_thing
    .links
      = link_to_add_association '+', f,
      :problem_things,
      class: 'btn btn-info spec__add-problem-things'
  = f.input :description
  = f.button :submit, class: 'btn btn-primary'

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 4.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", :role  => "alert"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-dark.bg-dark
  .container
    = link_to 'DAIKPT', root_url, class: 'text-white'
    .btn-group.mr-5
      %button.btn.btn-outline-primary.btn-sm.pr-3.pl-3.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"}
        メニュー
      .dropdown-menu.dropdown-menu-right
        %button.dropdown-item{:type => "button"}
          = link_to 'プロジェクト作成', new_project_path
        %button.dropdown-item{:type => "button"}
          = link_to 'プロジェクト一覧', projects_path
        %button.dropdown-item{:type => "button"}
          = link_to 'Keep一覧', keep_things_path
        %button.dropdown-item{:type => "button"}
          = link_to 'Try一覧', try_things_path

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Daikpt'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Daikpt'}"}
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      .container
        = yield

app/views/projects/index.html.haml
%h1.h3.page-header
  プロジェクト一覧
- if current_user.projects.blank?
  .alert.alert-warning
    所属プロジェクトがありません
  .jumbotron.text-center
    = image_tag '/images/top_main.png'
    %p プロジェクトを作成して、ふりかえりをしましょう！
    = link_to 'プロジェクト新規作成', new_project_path, class: 'btn btn-primary'
- else
  %table.table.table-striped
    %thead.thead-dark
      %tr
        %th{:scope => "col"} #
        %th{:scope => "col"} プロジェクト名
        %th{:scope => "col"} 最終更新日
        %th.text-center{:scope => "col"} 操作
    %tbody
      - @projects.each do |project|
        %tr
          %th{:scope => "row"} 1
          %td= link_to project.name, project_kpts_path(project)
          %td
            = project.kpts.last&.created_at
          %td.text-center
            = link_to 'ふりかえり開始', new_project_kpt_path(project), class: 'btn btn-outline-primary'

app/views/projects/new.html.haml
%h1.h2
  プロジェクト作成
= simple_form_for @project do |f|
  = f.input :name
  = f.button :submit, class: 'btn btn-primary'

app/views/try_things/index.html.haml
%table.table.table-bordered
  %tr.table-primary
    %th Try
    - @try_things.each do |try_thing|
      %tr
        %td
          - if try_thing.complete?
            %span.badge.badge-success.mr-3
              Keep済み
          = try_thing.content
          %p.float-right
            = try_thing.created_at.strftime('%Y年%m月%d日')

app/views/try_things/update.js.erb
var targetElement = $(".js-btn-change-keep[data-try-id='<%= @try_thing.id %>']")
targetElement.removeClass('btn-outline-success')
targetElement.addClass('disabled btn-outline-secondary')
targetElement.text('Keep済み')